From 93714b7db795b14b26adffde30753cfda0ca4867 Mon Sep 17 00:00:00 2001
From: "Miss Islington (bot)"
 <31488909+miss-islington@users.noreply.github.com>
Date: Wed, 23 Aug 2023 03:10:04 -0700
Subject: [PATCH] [3.11] gh-108342: Break ref cycle in SSLSocket._create() exc
 (GH-108344) (#108349)

Explicitly break a reference cycle when SSLSocket._create() raises an
exception. Clear the variable storing the exception, since the
exception traceback contains the variables and so creates a reference
cycle.

This test leak was introduced by the test added for the fix of GH-108310.
(cherry picked from commit 64f99350351bc46e016b2286f36ba7cd669b79e3)

Co-authored-by: Victor Stinner <vstinner@python.org>
---
 Lib/ssl.py | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

Origin: upstream, https://github.com/python/cpython/commit/93714b7db795b14b26adffde30753cfda0ca4867
Bug-Upstream: https://github.com/python/cpython/issues/108342
--- a/Lib/ssl.py
+++ b/Lib/ssl.py
@@ -1083,7 +1083,11 @@
                     self.close()
                 except OSError:
                     pass
-                raise notconn_pre_handshake_data_error
+                try:
+                    raise notconn_pre_handshake_data_error
+                finally:
+                    # Explicitly break the reference cycle.
+                    notconn_pre_handshake_data_error = None
         else:
             connected = True
 
